#!/bin/sh
set -e

ENV_JS_PATH="/usr/share/nginx/html/env.js"
PB_URL="${POCKETBASE_URL:-http://localhost:8080}"

PB_URL="${PB_URL%/}"

escaped_url=$(printf '%s' "$PB_URL" | sed -e 's/\\/\\\\/g' -e "s/'/\\\\'/g")

cat > "$ENV_JS_PATH" <<EOF
// Generated by docker/admin-entrypoint.sh at container startup.
// Source: env var POCKETBASE_URL.
window.__env = window.__env || {};
window.__env.POCKETBASE_URL = '${escaped_url}';
EOF

echo "[entrypoint] Wrote ${ENV_JS_PATH} with POCKETBASE_URL=${PB_URL}"

exec nginx -g 'daemon off;'
