#!/bin/sh
set -e

ENV_JS_PATH="/usr/share/nginx/html/env.js"
REDIRECT_INC="/etc/nginx/landing-redirect.inc"
RAW_URL="${POCKETBASE_URL:-}"
RAW_LANDING="${PUBLIC_BASE_URL:-}"

trimmed_url=$(printf '%s' "$RAW_URL" | tr -d '\r\n\t ')

if [ -z "$trimmed_url" ]; then
  PB_URL="http://localhost:8080"
  echo "[admin-entrypoint] WARNING: POCKETBASE_URL no seteada. Usando default ${PB_URL}."
  echo "[admin-entrypoint] En Dokploy: setear POCKETBASE_PUBLIC_URL en la pestaña Environment del servicio."
else
  PB_URL="${trimmed_url%/}"
fi

case "$PB_URL" in
  http://*|https://*) : ;;
  *)
    echo "[admin-entrypoint] WARNING: POCKETBASE_URL='${PB_URL}' no empieza con http:// o https://. Browser va a fallar."
    ;;
esac

trimmed_landing=$(printf '%s' "$RAW_LANDING" | tr -d '\r\n\t ')
LANDING_URL=""
if [ -n "$trimmed_landing" ]; then
  LANDING_URL="${trimmed_landing%/}"
  case "$LANDING_URL" in
    http://*|https://*) : ;;
    *)
      echo "[admin-entrypoint] WARNING: PUBLIC_BASE_URL='${LANDING_URL}' no empieza con http:// o https://. Links de comparativas van a fallar."
      ;;
  esac
fi

escaped_url=$(printf '%s' "$PB_URL" | sed -e 's/\\/\\\\/g' -e "s/'/\\\\'/g")
escaped_landing=$(printf '%s' "$LANDING_URL" | sed -e 's/\\/\\\\/g' -e "s/'/\\\\'/g")

cat > "$ENV_JS_PATH" <<EOF
// Generated by docker/admin-entrypoint.sh at container startup.
// POCKETBASE_URL ← compose POCKETBASE_PUBLIC_URL
// LANDING_URL    ← compose PUBLIC_BASE_URL (links /c/:token)
window.__env = window.__env || {};
window.__env.POCKETBASE_URL = '${escaped_url}';
window.__env.LANDING_URL = '${escaped_landing}';
EOF

if [ -n "$LANDING_URL" ]; then
  escaped_redir=$(printf '%s' "$LANDING_URL" | sed -e 's/[&]/\\&/g')
  cat > "$REDIRECT_INC" <<EOF
# Links viejos copiados desde el admin (/c/:token) → landing pública
location ^~ /c/ {
    return 302 ${escaped_redir}\$request_uri;
}
EOF
else
  echo "# PUBLIC_BASE_URL vacío: sin redirect /c/ → landing" > "$REDIRECT_INC"
fi

echo "[admin-entrypoint] Wrote ${ENV_JS_PATH}"
echo "[admin-entrypoint] Effective POCKETBASE_URL=${PB_URL}"
echo "[admin-entrypoint] Effective LANDING_URL=${LANDING_URL:-'(empty — JS usa loteoadmin→loteoweb)'}"

exec nginx -g 'daemon off;'
