#!/bin/sh
set -e

ENV_JS_PATH="/usr/share/nginx/html/env.js"
REDIRECT_INC="/etc/nginx/landing-redirect.inc"
RAW_URL="${POCKETBASE_URL:-}"
RAW_LANDING="${PUBLIC_BASE_URL:-}"

trimmed_url=$(printf '%s' "$RAW_URL" | tr -d '\r\n\t ')

if [ -z "$trimmed_url" ]; then
  PB_URL="http://localhost:8080"
  echo "[admin-entrypoint] WARNING: POCKETBASE_URL no seteada. Usando default ${PB_URL}."
  echo "[admin-entrypoint] En Dokploy: setear POCKETBASE_PUBLIC_URL en la pestaña Environment del servicio."
else
  PB_URL="${trimmed_url%/}"
fi

case "$PB_URL" in
  http://*|https://*) : ;;
  *)
    echo "[admin-entrypoint] WARNING: POCKETBASE_URL='${PB_URL}' no empieza con http:// o https://. Browser va a fallar."
    ;;
esac

trimmed_landing=$(printf '%s' "$RAW_LANDING" | tr -d '\r\n\t ')
LANDING_URL=""
if [ -n "$trimmed_landing" ]; then
  LANDING_URL="${trimmed_landing%/}"
  case "$LANDING_URL" in
    *=http://*|*=https://*)
      LANDING_URL="${LANDING_URL#*=}"
      ;;
  esac
  case "$LANDING_URL" in
    http://*|https://*) : ;;
    *)
      echo "[admin-entrypoint] WARNING: PUBLIC_BASE_URL='${LANDING_URL}' no es URL http(s). Ignorando."
      LANDING_URL=""
      ;;
  esac
  case "$LANDING_URL" in
    *://loteopb.*|*pocketbase*)
      echo "[admin-entrypoint] WARNING: PUBLIC_BASE_URL apunta a PocketBase (${LANDING_URL}). Ignorando."
      LANDING_URL=""
      ;;
  esac
fi

# printf '%s' — nunca unquoted heredoc: `$POCKETBASE_URL` / `$LANDING_URL` en
# `window.__env.POCKETBASE_URL` se expandían y rompían env.js.
{
  printf '%s\n' '// generated by docker/admin-entrypoint.sh'
  printf '%s\n' 'window.__env = window.__env || {};'
  printf "window.__env['POCKETBASE_URL'] = '%s';\n" "$(printf '%s' "$PB_URL" | sed -e "s/'/\\\\'/g")"
  printf "window.__env['LANDING_URL'] = '%s';\n" "$(printf '%s' "$LANDING_URL" | sed -e "s/'/\\\\'/g")"
} > "$ENV_JS_PATH"

if [ -n "$LANDING_URL" ]; then
  printf '%s\n' \
    "location ^~ /c/ {" \
    "    return 302 ${LANDING_URL}\$request_uri;" \
    "}" \
    > "$REDIRECT_INC"
else
  printf '%s\n' '# no PUBLIC_BASE_URL — sin redirect /c/' > "$REDIRECT_INC"
fi

echo "[admin-entrypoint] Wrote ${ENV_JS_PATH}"
echo "[admin-entrypoint] Effective POCKETBASE_URL=${PB_URL}"
echo "[admin-entrypoint] Effective LANDING_URL=${LANDING_URL:-'(empty — JS usa loteoadmin→loteoweb)'}"

exec nginx -g 'daemon off;'
