/// <reference path="../pb_data/types.d.ts" />

// Seed: creates the default admin user and the config singleton.
// Credentials: admin@loteomanager.com / admin1234
// IMPORTANT: Change these credentials after first boot.
//
// NOTE: PocketBase auto-generates the config record ID.
// The singleton is enforced by Hook 7 in main.pb.js (allows max 1 record).

migrate((app) => {
  // --- 1. Create admin user ---
  const usersCollection = app.findCollectionByNameOrId("users");

  const admin = new Record(usersCollection);
  admin.set("email", "admin@loteomanager.com");
  admin.set("name", "Administrador");
  admin.set("role", "admin");
  admin.set("activo", true);
  admin.set("leads_visibility", "todos");
  admin.set("emailVisibility", true);
  admin.setPassword("admin1234");
  admin.set("verified", true);

  app.save(admin);

  // --- 2. Create config singleton (ID auto-generated by PocketBase) ---
  const configCollection = app.findCollectionByNameOrId("config");

  const config = new Record(configCollection);
  config.set("responsable_default_id", admin.id);
  config.set("whatsapp_notif_enabled", true);
  config.set("email_notif_enabled", true);
  config.set("comparativa_expiracion_default_dias", 30);

  app.save(config);
}, (app) => {
  try {
    const records = app.findAllRecords("config");
    for (const r of records) { app.delete(r); }
  } catch (_e) {}

  try {
    const records = app.findRecordsByFilter(
      "users",
      "email = 'admin@loteomanager.com'",
      "-created", 10, 0,
    );
    for (const r of records) { app.delete(r); }
  } catch (_e) {}
});
